name: Laravel CI

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SCRIPT_AFTER: |
          cd ${{ secrets.REMOTE_TARGET }}
          php artisan down
          npm install
          npm run build --if-present
          composer install --no-interaction --no-progress --no-suggest --prefer-dist
          php artisan storage:link --quiet
          php artisan migrate --force
          php artisan optimize:clear
          chmod -R 755 storage/* bootstrap/cache
          chown -R ${{ secrets.REMOTE_USER }}:${{ secrets.REMOTE_USER }} *
          php artisan up