name: Build and Deploy to Coolify

on:
  push:
    branches: [ production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.COOLIFY_REGISTRY_URL }}
        username: ${{ secrets.COOLIFY_REGISTRY_USERNAME }}
        password: ${{ secrets.COOLIFY_REGISTRY_PASSWORD }}

    - name: Extract repository name
      run: echo "REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ github.sha }}

    - name: Deploy to Coolify
      env:
        COOLIFY_DEPLOYMENT_KEY: ${{ secrets.COOLIFY_DEPLOYMENT_KEY }}
        COOLIFY_URL: ${{ secrets.COOLIFY_URL }}
        COOLIFY_SERVICE_ID: ${{ secrets.COOLIFY_SERVICE_ID }}
      run: |
        curl -X POST "$COOLIFY_URL/api/v1/services/$COOLIFY_SERVICE_ID/redeploy" \
        -H "Authorization: Bearer $COOLIFY_DEPLOYMENT_KEY" \
        -H "Content-Type: application/json" \
        -d '{"imageUrl": "${{ secrets.COOLIFY_REGISTRY_URL }}/${{ env.REPO_NAME }}:${{ github.sha }}"}'